import jsPDF from "jspdf";

export interface PayslipPDFData {
  id: string;
  employeeName: string;
  employeeId?: string;
  department?: string;
  position?: string;
  period: string;
  contractRef?: string;
  gross: number;
  deductions: number;
  net: number;
  lines: Array<{
    rule: string;
    category: string;
    amount: number;
    type: "EARNING" | "DEDUCTION";
  }>;
}

export function generatePayslipPDF(data: PayslipPDFData) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Theme Colors
  const darkInk = [22, 27, 34] as const;
  const mutedGray = [107, 114, 128] as const;
  const borderLine = [229, 227, 221] as const;
  const accentGold = [184, 134, 46] as const;

  // Header Banner
  doc.setFillColor(...darkInk);
  doc.rect(0, 0, 210, 24, "F");

  doc.setTextColor(250, 250, 248);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("PEOPLEPAY360", 14, 15);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("OFFICIAL SALARY LEDGER STATEMENT", 14, 20);

  doc.text(`Ref: ${data.id}`, 196, 15, { align: "right" });
  doc.text(`Period: ${data.period}`, 196, 20, { align: "right" });

  // Employee & Company Details Box
  let y = 35;
  doc.setTextColor(...darkInk);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("EMPLOYEE SUMMARY", 14, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...mutedGray);

  y += 7;
  doc.text("Employee Name:", 14, y);
  doc.setTextColor(...darkInk);
  doc.setFont("helvetica", "bold");
  doc.text(data.employeeName, 55, y);

  if (data.employeeId) {
    y += 5;
    doc.setTextColor(...mutedGray);
    doc.setFont("helvetica", "normal");
    doc.text("Employee ID:", 14, y);
    doc.setTextColor(...darkInk);
    doc.setFont("courier", "bold");
    doc.text(data.employeeId, 55, y);
  }

  if (data.department) {
    y += 5;
    doc.setTextColor(...mutedGray);
    doc.setFont("helvetica", "normal");
    doc.text("Department:", 14, y);
    doc.setTextColor(...darkInk);
    doc.text(data.department, 55, y);
  }

  if (data.contractRef) {
    y += 5;
    doc.setTextColor(...mutedGray);
    doc.setFont("helvetica", "normal");
    doc.text("Contract Ref:", 14, y);
    doc.setTextColor(...darkInk);
    doc.setFont("courier", "normal");
    doc.text(data.contractRef, 55, y);
  }

  // Divider
  y += 8;
  doc.setDrawColor(...borderLine);
  doc.setLineWidth(0.4);
  doc.line(14, y, 196, y);

  // Table Header
  y += 8;
  doc.setFillColor(245, 245, 242);
  doc.rect(14, y, 182, 8, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...darkInk);
  doc.text("SALARY COMPONENT / RULE", 18, y + 5.5);
  doc.text("CATEGORY", 115, y + 5.5);
  doc.text("AMOUNT (USD)", 192, y + 5.5, { align: "right" });

  // Table Lines
  y += 9;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  data.lines.forEach((line) => {
    y += 6;
    doc.setTextColor(...darkInk);
    doc.text(line.rule, 18, y);

    doc.setFont("courier", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...mutedGray);
    doc.text(line.category, 115, y);

    doc.setFontSize(9);
    if (line.type === "DEDUCTION") {
      doc.setTextColor(168, 68, 47); // Red for deduction
      doc.text(`-${Math.abs(line.amount).toFixed(2)}`, 192, y, { align: "right" });
    } else {
      doc.setTextColor(...darkInk);
      doc.text(`$${line.amount.toFixed(2)}`, 192, y, { align: "right" });
    }
    doc.setFont("helvetica", "normal");
  });

  // Totals Box
  y += 12;
  doc.setDrawColor(...borderLine);
  doc.line(14, y, 196, y);

  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...mutedGray);
  doc.text("Total Gross Earnings:", 120, y);
  doc.setTextColor(...darkInk);
  doc.setFont("courier", "bold");
  doc.text(`$${data.gross.toFixed(2)}`, 192, y, { align: "right" });

  y += 6;
  doc.setTextColor(...mutedGray);
  doc.setFont("helvetica", "normal");
  doc.text("Total Deductions:", 120, y);
  doc.setTextColor(168, 68, 47);
  doc.setFont("courier", "bold");
  doc.text(`-$${data.deductions.toFixed(2)}`, 192, y, { align: "right" });

  y += 4;
  doc.setFillColor(...accentGold);
  doc.rect(115, y, 81, 10, "F");

  doc.setTextColor(250, 250, 248);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("NET SALARY:", 120, y + 6.5);
  doc.setFont("courier", "bold");
  doc.setFontSize(11);
  doc.text(`$${data.net.toFixed(2)}`, 192, y + 6.5, { align: "right" });

  // Footer
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...mutedGray);
  doc.text("Generated by PeoplePay360 Integrated HR & Payroll Ledger", 14, 285);
  doc.text(new Date().toLocaleDateString("en-US", { dateStyle: "long" }), 196, 285, { align: "right" });

  // Trigger download
  doc.save(`Payslip_${data.id}_${data.employeeName.replace(/\s+/g, "_")}.pdf`);
}
